spring.application.name=service-agendamiento
server.port=8083

# Conexion a XAMPP MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_agendamiento?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# Estrategia de creacion de tablas
spring.jpa.hibernate.ddl-auto=update

# Logs SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

barberia.service-clientes.url=http://localhost:8082
barberia.service-barberos.url=http://localhost:8084
barberia.service-servicios.url=http://localhost:8085
